import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Blog(props) {
  const { posts } = props;
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat"
          rel="stylesheet"
          type="text/css"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </Head>
      <nav className="navbar navbar-default navbar-fixed-top">
        <div className="container">
          <div className="navbar-header">
            <button
              type="button"
              className="navbar-toggle"
              data-toggle="collapse"
              data-target="#myNavbar"
            >
              <span className="icon-bar"></span>
              <span className="icon-bar"></span>
              <span className="icon-bar"></span>
            </button>
            <a className="navbar-brand" href="/">
              Logo
            </a>
          </div>
          <div className="collapse navbar-collapse" id="myNavbar">
            <ul className="nav navbar-nav navbar-right">
              <li>
                <a href="/blogs">BLOGS</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div className="container" style={{ marginTop: '25px' }}>
        <div className={`row ${styles.row}`}>
          {posts.map((blog, index) => (
            <Link
              key={blog.url}
              href={{
                pathname: "/blogs/detail",
                query: { id: blog.url },
              }}
            >
              <div className="col-sm-4">
                <div className="thumbnail">
                  <img
                    src={blog.urlToImage}
                    alt="New York"
                    width="400"
                    height="300"
                  />
                  <p>
                    <strong>{blog.title}</strong>
                  </p>
                  <p>{blog.publishedAt = new Date().toDateString()}</p>
                  {/* <button
                    className="btn"
                    data-toggle="modal"
                    data-target="#myModal"
                  >
                    Buy Tickets
                  </button> */}
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
