import Head from "next/head";
import Image from "next/image";
import axios from 'axios';
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import Link from 'next/link'

export default function Home() {
  const [myBanner, setMyBanner] = useState([]);

  useEffect(() => {
    async function fetchPostList() {
      // ... goi api nen dung try catch de tranh loi xay ra
      try {
        axios.get('https://newsapi.org/v2/everything?domains=wsj.com&apiKey=d326a2552a9b4219b1c050c52f18c48b').then(res => {
          setMyBanner(res.data.articles.splice(0, 5));
          localStorage.setItem("blogs", JSON.stringify(res.data.articles));
        });
      } catch (error) {
        throw error;
      }
    }
    fetchPostList();
    console.log(myBanner);
  }, []);// empty array chi chay dung 1 lan, khong bi phu thuoc 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat"
          rel="stylesheet"
          type="text/css"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </Head>

      <nav className="navbar navbar-default navbar-fixed-top">
          <div className="container">
            <div className="navbar-header">
              <button
                type="button"
                className="navbar-toggle"
                data-toggle="collapse"
                data-target="#myNavbar"
              >
                <span className="icon-bar"></span>
                <span className="icon-bar"></span>
                <span className="icon-bar"></span>
              </button>
              <a className="navbar-brand" href="#myPage">
                Home
              </a>
            </div>
            <div className="collapse navbar-collapse" id="myNavbar">
              <ul className="nav navbar-nav navbar-right">
                <li>
                  <a href="/blogs">BLOGS</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div id="myCarousel" className="carousel slide" data-ride="carousel">
          <ol className="carousel-indicators">
            <li
              data-target="#myCarousel"
              data-slide-to="0"
              className="active"
            ></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>
          </ol>

          <div className={`carousel-inner `} pl="carousel-inner" role="listbox">
            {myBanner.map((blog, index) => (
                <div key={index} className={index === 0? 'item active': 'item'}>
                  <img src={blog.urlToImage} alt="Chicago" />
                  <div className="carousel-caption">
                    <h2>{blog.title}</h2>
                    <p>{blog.content}</p>
                  </div>
                </div>
              ))
            }
          </div>

          <a
            className="left carousel-control"
            href="#myCarousel"
            role="button"
            data-slide="prev"
          >
            <span
              className="glyphicon glyphicon-chevron-left"
              aria-hidden="true"
            ></span>
            <span className="sr-only">Previous</span>
          </a>
          <a
            className="right carousel-control"
            href="#myCarousel"
            role="button"
            data-slide="next"
          >
            <span
              className="glyphicon glyphicon-chevron-right"
              aria-hidden="true"
            ></span>
            <span className="sr-only">Next</span>
          </a>
        </div>

      {/* banner */}
      <main>
        
        <div id="band" className="container text-center">
          <h3>THE BAND</h3>
          <p>
            <em>We love music!</em>
          </p><br/>
          <p>
            We have created a fictional band website. Lorem ipsum dolor sit
            amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
            ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit
            esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
            cupidatat non proident, sunt in culpa qui officia deserunt mollit
            anim id est laborum consectetur adipiscing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
            veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
            ea commodo consequat.
          </p>
            <br/><br/>
          {/* <div className={`row ${styles.row}`}>
            {myBanner.map((blog, index) => ( 
              <Link
              key={blog.url}
              href={{
                pathname: '/blogs/detail',
                query: { id: blog.url },
              }}
            >
              <div key={index}  className={`col-sm-4 ${styles.item}`}>
                <div className={`thumbnail ${styles.thumbnail}`}>
                  <img
                    src={blog.urlToImage}
                    alt="San Francisco"
                    width="400"
                    height="300"
                  />
                  <p>
                    <strong>{blog.title}</strong>
                  </p>
                  <p>{blog.publishedAt = new Date().toDateString()}</p>
                  <button
                    className="btn"
                    data-toggle="modal"
                    data-target="#myModal"
                  >
                    Buy Tickets
                  </button>
                </div>
              </div>
            </Link>
            ))}
          </div> */}
        </div>

        {/* <div id="tour" className="bg-1">
          <div className="container">
            <h3 className="text-center">TOUR DATES</h3>
            <p className="text-center">
              Lorem ipsum we'll play you some music. Remember to book your
              tickets!
            </p>
            <ul className="list-group">
              <li className="list-group-item">
                September <span className="label label-danger">Sold Out!</span>
              </li>
              <li className="list-group-item">
                October <span className="label label-danger">Sold Out!</span>
              </li>
              <li className="list-group-item">
                November <span className="badge">3</span>
              </li>
            </ul>

            <div className="row text-center">
              <div className="col-sm-4">
                <div className="thumbnail">
                  <img src="paris.jpg" alt="Paris" width="400" height="300" />
                  <p>
                    <strong>Paris</strong>
                  </p>
                  <p>Friday 27 November 2015</p>
                  <button
                    className="btn"
                    data-toggle="modal"
                    data-target="#myModal"
                  >
                    Buy Tickets
                  </button>
                </div>
              </div>
              <div className="col-sm-4">
                <div className="thumbnail">
                  <img
                    src="newyork.jpg"
                    alt="New York"
                    width="400"
                    height="300"
                  />
                  <p>
                    <strong>New York</strong>
                  </p>
                  <p>Saturday 28 November 2015</p>
                  <button
                    className="btn"
                    data-toggle="modal"
                    data-target="#myModal"
                  >
                    Buy Tickets
                  </button>
                </div>
              </div>
              <div className="col-sm-4">
                <div className="thumbnail">
                  <img
                    src="sanfran.jpg"
                    alt="San Francisco"
                    width="400"
                    height="300"
                  />
                  <p>
                    <strong>San Francisco</strong>
                  </p>
                  <p>Sunday 29 November 2015</p>
                  <button
                    className="btn"
                    data-toggle="modal"
                    data-target="#myModal"
                  >
                    Buy Tickets
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div className="modal fade" id="myModal" role="dialog">
            <div className="modal-dialog">
              <div className="modal-content">
                <div className="modal-header">
                  <button type="button" className="close" data-dismiss="modal">
                    ×
                  </button>
                  <h4>
                    <span className="glyphicon glyphicon-lock"></span> Tickets
                  </h4>
                </div>
                <div className="modal-body">
                  <htmlForm role="htmlForm">
                    <div className="htmlForm-group">
                      <label htmlFor="psw">
                        <span className="glyphicon glyphicon-shopping-cart"></span>{" "}
                        Tickets, $23 per person
                      </label>
                      <input
                        type="number"
                        className="htmlForm-control"
                        id="psw"
                        placeholder="How many?"
                      />
                    </div>
                    <div className="htmlForm-group">
                      <label htmlFor="usrname">
                        <span className="glyphicon glyphicon-user"></span> Send
                        To
                      </label>
                      <input
                        type="text"
                        className="htmlForm-control"
                        id="usrname"
                        placeholder="Enter email"
                      />
                    </div>
                    <button type="submit" className="btn btn-block">
                      Pay
                      <span className="glyphicon glyphicon-ok"></span>
                    </button>
                  </htmlForm>
                </div>
                <div className="modal-footer">
                  <button
                    type="submit"
                    className="btn btn-danger btn-default pull-left"
                    data-dismiss="modal"
                  >
                    <span className="glyphicon glyphicon-remove"></span> Cancel
                  </button>
                  <p>
                    Need <a href="#">help?</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div id="contact" className="container">
          <h3 className="text-center">Contact</h3>
          <p className="text-center">
            <em>We love our fans!</em>
          </p>

          <div className="row">
            <div className="col-md-4">
              <p>Fan? Drop a note.</p>
              <p>
                <span className="glyphicon glyphicon-map-marker"></span>Chicago,
                US
              </p>
              <p>
                <span className="glyphicon glyphicon-phone"></span>Phone: +00
                1515151515
              </p>
              <p>
                <span className="glyphicon glyphicon-envelope"></span>Email:
                mail@mail.com
              </p>
            </div>
            <div className="col-md-8">
              <div className="row">
                <div className="col-sm-6 htmlForm-group">
                  <input
                    className="htmlForm-control"
                    id="name"
                    name="name"
                    placeholder="Name"
                    type="text"
                    required
                  />
                </div>
                <div className="col-sm-6 htmlForm-group">
                  <input
                    className="htmlForm-control"
                    id="email"
                    name="email"
                    placeholder="Email"
                    type="email"
                    required
                  />
                </div>
              </div>
              <textarea
                className="htmlForm-control"
                id="comments"
                name="comments"
                placeholder="Comment"
                rows="5"
              ></textarea>

              <div className="row">
                <div className="col-md-12 htmlForm-group">
                  <button className="btn pull-right" type="submit">
                    Send
                  </button>
                </div>
              </div>
            </div>
          </div>
          <h3 className="text-center">From The Blog</h3>
          <ul className="nav nav-tabs">
            <li className="active">
              <a data-toggle="tab" href="#home">
                Mike
              </a>
            </li>
            <li>
              <a data-toggle="tab" href="#menu1">
                Chandler
              </a>
            </li>
            <li>
              <a data-toggle="tab" href="#menu2">
                Peter
              </a>
            </li>
          </ul>

          <div className="tab-content">
            <div id="home" className="tab-pane fade in active">
              <h2>Mike Ross, Manager</h2>
              <p>
                Man, we've been on the road htmlFor some time now. Looking htmlForward
                to lorem ipsum.
              </p>
            </div>
            <div id="menu1" className="tab-pane fade">
              <h2>Chandler Bing, Guitarist</h2>
              <p>
                Always a pleasure people! Hope you enjoyed it as much as I did.
                Could I BE.. any more pleased?
              </p>
            </div>
            <div id="menu2" className="tab-pane fade">
              <h2>Peter Griffin, Bass player</h2>
              <p>
                I mean, sometimes I enjoy the show, but other times I enjoy
                other things.
              </p>
            </div>
          </div>
        </div>
         */}
      </main>

      <footer className="text-center">
        <a
          className="up-arrow"
          href="#myPage"
          data-toggle="tooltip"
          title="TO TOP"
        >
          <span className="glyphicon glyphicon-chevron-up"></span>
        </a>
        <p>
          Bootstrap Theme Made By{" "}
          <a
            href="https://www.w3schools.com"
            data-toggle="tooltip"
            title="Visit w3schools"
          >
            www.w3schools.com
          </a>
        </p>
      </footer>
    </div>
  );
}
