import Head from "next/head";
import Image from "next/image";
import axios from 'axios';
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import Link from 'next/link';
import useTrans from './hooks/useTrans'
import { useRouter } from "next/router"

export default function Home() {
  const [myBanner, setMyBanner] = useState([]);
  const trans = useTrans();
  const router = useRouter()

  useEffect(() => {
    async function fetchPostList() {
      // ... goi api nen dung try catch de tranh loi xay ra
      try {
        axios.get('https://newsapi.org/v2/everything?domains=wsj.com&apiKey=d326a2552a9b4219b1c050c52f18c48b').then(res => {
          setMyBanner(res.data.articles.splice(0, 5));
          localStorage.setItem("blogs", JSON.stringify(res.data.articles));
        });
      } catch (error) {
        throw error;
      }
    }
    fetchPostList();
    console.log(myBanner);
  }, []);// empty array chi chay dung 1 lan, khong bi phu thuoc 

  const changeLang = (lang) => {
    router.push('/', '/', { locale: lang });
  }

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat"
          rel="stylesheet"
          type="text/css"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </Head> */}
      {/* <nav className="navbar navbar-default navbar-fixed-top">
          <div className="container">
            <div className="navbar-header">
              <button
                type="button"
                className="navbar-toggle"
                data-toggle="collapse"
                data-target="#myNavbar"
              >
                <span className="icon-bar"></span>
                <span className="icon-bar"></span>
                <span className="icon-bar"></span>
              </button>
              <a className="navbar-brand" href="/">
              { trans.navbar.home }
              </a>
            </div>
            <div className="collapse navbar-collapse" id="myNavbar">
              <ul className="nav navbar-nav navbar-right">
                <li>
                  <a href="/blogs"> { trans.navbar.blogs }</a>
                </li>
                <li className="dropdown">
                  <a className="dropdown-toggle" data-toggle="dropdown" href="#">Language
                  <span className="caret"></span></a>
                  <ul className="dropdown-menu">
                    <li><a onClick={() => changeLang('vi')}  href="#">vi</a></li>
                    <li><a onClick={() => changeLang('en')} href="#">en</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav> */}
        <div id="carouselExampleControls" className="carousel slide" data-ride="carousel">
          <div className="carousel-inner">
              {myBanner.map((blog, index) => (
                  <div key={index} className={index === 0 ? 'carousel-item active': 'carousel-item'}>
                    <img src={blog.urlToImage} alt={blog.title} />
                    <div className="carousel-caption">
                      <h2>{blog.title}</h2>
                      <p>{blog.content}</p>
                    </div>
                  </div>
                ))
              }
          </div>
          <a className="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span className="carousel-control-prev-icon" aria-hidden="true"></span>
            <span className="sr-only">Previous</span>
          </a>
          <a className="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span className="carousel-control-next-icon" aria-hidden="true"></span>
            <span className="sr-only">Next</span>
          </a>
      </div>

      {/* <h1 className={styles.title}>
        { trans.home.title }
      </h1>

      <p className={styles.description}>
          { trans.home.content }
      </p> */}
      {/* banner */}
      <main>
        <div id="band" className="container text-center">
          <h3>THE BAND</h3>
          <p>
            <em>We love music!</em>
          </p><br/>
          <p>
            We have created a fictional band website. Lorem ipsum dolor sit
            amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
            ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit
            esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
            cupidatat non proident, sunt in culpa qui officia deserunt mollit
            anim id est laborum consectetur adipiscing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
            veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
            ea commodo consequat.
          </p>
            <br/><br/>
        </div>
      </main>

      <footer className="text-center">
        <a
          className="up-arrow"
          href="#myPage"
          data-toggle="tooltip"
          title="TO TOP"
        >
          <span className="glyphicon glyphicon-chevron-up"></span>
        </a>
        <p>
          Bootstrap Theme Made By{" "}
          <a
            href="https://www.w3schools.com"
            data-toggle="tooltip"
            title="Visit w3schools"
          >
            www.w3schools.com
          </a>
        </p>
      </footer>
    </div>
  );
}
