import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuerySubscription } from "react-datocms"
import { useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  // const { status, error, data } = useQuerySubscription({
  //   enabled: true,
  //   query: `
  //   query MyQuery {
  //     allPosts {
  //       id
  //       slug
  //       title
  //       excerpt
  //       coverImage {
  //         id
  //         url
  //       }
  //     }
  //   }`,
  //   variables: { first: 10 },
  //   token: "a09129da379553e1cc40a4093891c0",
  // });

  let data = [];

  const statusMessage = {
    connecting: "Connecting to DatoCMS...",
    connected: "Connected to DatoCMS, receiving live updates!",
    closed: "Connection closed",
  };
  useEffect(() => {
    axios.get('http://localhost:1337/blogs').then(res => {
      console.log(res.data);
      data = res.data;
    });
  });
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          pádasd
        </h1>

        {/* <div className={styles.description}>
          <div>
            <p>Connection status: {statusMessage[status]}</p>
            {error && (
              <div>
                <h1>Error: {error.code}</h1>
                <div>{error.message}</div>
                {error.response && (
                  <pre>{JSON.stringify(error.response, null, 2)}</pre>
                )}
              </div>
            )}
          </div>
        </div> */}

        {/* {data &&  */}
          <div className={styles.grid}>
          {data.map((blog) => (
            
              <a key={blog.id} className={styles.card} href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
                <img src={blog.imgURL} className={styles.img}></img>
                <h2>{blog.title}</h2>
                <p>{blog.content}</p><p>len</p>
              </a>
          ))}
          </div>
        {/* } */}
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
