import React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Edit() {
  return (
    <div className="container">
      <Head>
        <title>Edit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Lato"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat"
          rel="stylesheet"
          type="text/css"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </Head>
      <div className={styles.edit}>
        {/* {console.log(
           "LOG -> file: detail.js -> line 16 -> useEffect -> setMyBlog",
           myBlog
       )} */}
        <div className="row">
          <div className="col-sm-12">
            <h2 className={styles.title}>Edit blog</h2>
            {/* {myBlog && (
               <a key={myBlog.url} className={styles.card}>
               <img src={myBlog.urlToImage} className={styles.img}></img>
               <h2>{myBlog.title}</h2>
               <p>{myBlog.content}</p>
               </a>
           )} */}
            <div className="form-group">
              <label for="usr">Name:</label>
              <input type="text" className="form-control" id="usr" />
            </div>
            <div className="form-group">
              <label for="pwd">Password:</label>
              <input type="password" class="form-control" id="pwd" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
